### ISSUE TITLE
Render function handles too much

### ISSUE THREAD

**Issue by aidanbell** [salmafarah/IT-Game#6]
Your render function seems to not only handle putting elements onto the page. The function that you run after the user has guessed should handle all of the logic to find out if the question was right or wrong, and then style the button accordingly. This doesn't all have to be done in one function. You could have a function that handles styling changes, can call that according to the button pressed. This way, you can call your render function when the "Next Question" button is pressed to clear all classes that you may have added and display the next. 

https://github.com/salmafarah/IT-Game/blob/758572aa9c7ac24b4a159b42068679ec5c3d7393/JS/main.js#L231-L269

**Comment by jtuppy** [comment]
I know I helped with this one. This render function allows the buttons to maintain state after switching between questions. Yes, another render function could be used on Next / Previous, but this will update all the buttons no matter what question you go to
